giftcardreader: giftcardreader.c
	gcc -g -o giftcardreader giftcardreader.c && ./giftcardreader 1 examplefile.gft


giftcardexamplewriter:
	gcc -g -o giftcardexamplewriter giftcardexamplewriter.c && ./giftcardexamplewriter


